### PR TITLE
Fixes IProgress<stream> for v1.13

### LINKED ISSUE #108: Tasks that return status streams should be replaced with calls to IProgress<StreamStatus>
Methods that return a `Task<Stream>` like `PullImageAsync` could instead return `Task<IProgress<Stream>>` to abstract away some of the details of how docker reports it's progress.  This should simplify patterns for callers who want to report that progress.

@jterry75 Can expand on what we are looking for here.

### PR DESCRIPTION
**Pull request by jterry75**
Resolves #108.

Full implements the IProgress<Stream> changes for the v1.13 api change
using JSONMessage JSONProgress and JSONError

### CODE REVIEW

**Comment by jterry75** [comment]
@galvesribeiro - After this is merged. I will update to the final v1.13 that was released from docker (if any changes). Then merge that branch back to mainline master! Almost there! Thanks for all the help

**Comment by galvesribeiro** [comment]
Thank you all for being so helpful :)

After everything get done, I'll have a look at set the tests up. :)

**Comment by pbielinski** [comment]
IMO obsolete annotation was set on incorrect method GetContainerLogsAsync with IProgress

**Comment by jterry75** [comment]
@pbielinski - You are 100% correct!

**Pull request merged**
