### PR TITLE
Implements the Swarm Task's API

### PR DESCRIPTION
**Pull request by jterry75**
Resolves: #158

### CODE REVIEW

**Comment by galvesribeiro** [comment]
@jterry75 I only have 1 question... Why [TaskResponse](https://github.com/Microsoft/Docker.DotNet/pull/228/files#diff-b1361d745fe87c1826eb153cffcc4e2b) isn't being generated by the codegen from Go source like all other models? (just curious)

**Comment by jterry75** [comment]
I was looking at the API and absent minded just wrote the model. I have updated the PR with the automated changes. (And good thing, the documentation is missing some the models allow!)

**Comment by galvesribeiro** [comment]
Yeah... There are some stuff not well documented there.

I wish we could move to use Swagger and drop the codegen. Would make our life easier.

**Comment by jterry75** [comment]
> I wish we could move to use Swagger and drop the codegen. Would make our life easier.

I haven't given up here. Thinking I might just write a yaml to roslyn transform and then we absolutely can do this for both the models and the api. But will take some time.

**Comment by galvesribeiro** [comment]
> Thinking I might just write a yaml to roslyn transform

Yes, that was my initial plan. I thought on use https://www.nuget.org/packages/YamlDotNet/4.2.1

It would make us have 2 things:

1. Drop the Go codegen and use the yaml spec
2. Have the codegen be able to run either in compile or runtime mode -> Runtime mode will allow live update to new APIs. We have something like that in Orleans for Serializers.

**Comment by jterry75** [comment]
Exactly. Although in practice the API isn't likely to change very often and simply being able to take 1 stamp per release and rerun the codegen should be sufficient. Its just that we today have to do a lot of manual work to figure out what the API even is from code rater than from the yaml.

**Pull request merged**
