### PR TITLE
Implements MultiplexedStream ReadToEndAsync

### PR DESCRIPTION
**Pull request by jterry75**
Resolves: #264

### CODE REVIEW

**Comment by jterry75** [comment]
@aemery - I have not tried this but let me know if this is what you were looking for.

**Comment by aemery** [comment]
This is indeed what I'm looking for. The output is not what I would expect though.

Command: powershell Get-Item 'HKLM:/SOFTWARE/ODBC/ODBCINST.INI/ODBC Drivers' | Select -ExpandProperty Property

Expected output: PostgreSQL ANSI(x64)\r\nPostgreSQL Unicode(x64)\r\nSQL Server
What I'm getting: "PostgreSQL ANSI(x64)PostgreSQL ANSI(x64)\r\nPostgreSQL Unicod" or "PostgreSQL ANSI(x64)\r\nPostgreSQL ANSI(x64)\r\nPPoPostgreSQLPo" (output is not constant when running the same code multiple times)

Using the REST Api directly (using Postman), I get the correct expected output.

**Comment by aemery** [comment]
Sleeping between StartWithConfigContainerExecAsync and ReadOutputToEndAsync fixes it. Is there a way to ensure that the output is fully available before reading it? I'm basically trying to get the same behavior as calling docker exec or /exec/id/start in attached mode.

**Comment by jterry75** [comment]
Ok looked at this harder. I understand the issue your hitting with this code fix. I can provide a better impl if you are ok with this assumption. Otherwise You really should use `CopyOutputToAsync` yourself because you know how it was configured.

`ReadOutToEndAsync` will really need to return a` Task<(string, string)>` where the results are `stdout, stderr`. Because on a true multiplexed stream we cannot assume that the output is just `stdout` or just `stderr` and there is no way to know how to make a single string from the output if using both.

**Comment by galvesribeiro** [comment]
@jterry75  did you finished the implementation so can I have a look on it?

**Comment by jterry75** [comment]
I did but I was hoping that @aemery would tell me if it solves his situation before we merge.

**Comment by aemery** [comment]
Sorry for the delay, having the two output separated is ok for me. If you can provide a fix for the issue I mentionned above, I'm good with receiving a Task<(string, string)>.

**Comment by jterry75** [comment]
@aemery - I actually pushed another fix already that should work and give you the full output. Want to give it a shot?

**Comment by aemery** [comment]
Just tested your last fix. Works great.

**Pull request merged**
